# GradNorm

In [2]:
import torch

## 核心算法实现

## 知识点

### torch.autograd.grad()

In [16]:
x = torch.randn(3, 4).requires_grad_(True)
y = x ** 2

In [17]:
print(x)
print(y)

tensor([[ 1.4723, -0.0594, -0.1338, -0.2229],
        [ 0.7621, -0.7576,  0.3284,  2.2155],
        [-0.2245,  0.8085, -0.1903,  1.0938]], requires_grad=True)
tensor([[2.1678e+00, 3.5258e-03, 1.7892e-02, 4.9700e-02],
        [5.8076e-01, 5.7394e-01, 1.0784e-01, 4.9085e+00],
        [5.0422e-02, 6.5367e-01, 3.6218e-02, 1.1964e+00]],
       grad_fn=<PowBackward0>)


In [18]:
weight = torch.ones(y.size())
print(weight)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
dydx = torch.autograd.grad(outputs=y,
                           inputs=x,
                           grad_outputs=weight,
                           retain_graph=True,
                           create_graph=True,
                           only_inputs=True)

In [20]:
"""(x**2)' = 2*x """
print(dydx)

(tensor([[ 2.9447, -0.1188, -0.2675, -0.4459],
        [ 1.5241, -1.5152,  0.6568,  4.4310],
        [-0.4491,  1.6170, -0.3806,  2.1876]], grad_fn=<MulBackward0>),)


In [21]:
d2ydx2 = torch.autograd.grad(outputs=dydx[0],
                             inputs=x,
                             grad_outputs=weight,
                             retain_graph=True,
                             create_graph=True,
                             only_inputs=True)
print(d2ydx2[0])

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], grad_fn=<MulBackward0>)


### requires_grad测试

In [108]:
X = torch.ones((2, 2), requires_grad=True)
M = torch.ones((2, 2), requires_grad=True)

In [99]:
y = X + 2 + M

In [100]:
y

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)

In [101]:
z = y * y * 3

In [102]:
z = torch.tensor(z)

<ipython-input-102-222cd23f619f>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z = torch.tensor(z)


In [103]:
z = z.mean()

In [104]:
torch.autograd.grad(z, M)[0]

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [107]:
torch.mul(torch.tensor([1, 2]), torch.tensor([2, 3]))

tensor([2, 6])